Repository accentor/api-client-js, pull requests merged in 2021-08, with the labels that each got.

#27 Convert library to typescript
  .eslintrc.js
  build.js
  esbuild.js
  package.json
  src/api_module.js
  src/api_module.ts
  src/http.ts
  src/index.ts
  src/scopes.ts
  src/types/album.ts
  src/types/artist.ts
  src/types/auth.ts
  src/types/codec.ts
  src/types/codec_conversion.ts
  src/types/cover_filename.ts
  src/types/fetch_retry.ts
  src/types/genre.ts
  src/types/image_type.ts
  src/types/label.ts
  src/types/location.ts
  src/types/play.ts
  src/types/rescan.ts
  src/types/shared.ts
  src/types/track.ts
  src/types/user.ts
  tsconfig.json
  vendor/fetch-retry/types.ts
  yarn.lock
Labels: refactor

#29 Make fields of ImageParams optional for compatibility with api 0.12
  src/types/shared.ts
Labels: enhancement

#30 Don't set "noEmit" to make sure npm-dts can emit
  tsconfig.json
Labels: bug

#31 Fix occurences where we still used `path` instead of `url`
  src/api_module.ts
Labels: bug

#33 Allow plays to be scoped by album
  src/api_module.ts
  src/scopes.ts
Labels: enhancement
