Repository accentor/api-client-js, pull requests merged in 2021-07, with the labels that each got.

#1 Create basic api client
  .eslintrc.js
  README.md
  package.json
  src/api_module.js
  src/index.js
  yarn.lock
Labels: enhancement

#2 Add plays to modules
  src/index.js
Labels: enhancement

#8 Rename merge param to `source_id`
  src/api_module.js
Labels: enhancement

#9 Update issue and pull request templates
  .github/ISSUE_TEMPLATE.md/bug_report.md
  .github/ISSUE_TEMPLATE.md/feature_request.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#5 Add scopes
  .eslintrc.js
  README.md
  package.json
  src/api_module.js
  src/index.js
  src/scopes.js
  yarn.lock
Labels: enhancement

#6 Setup release structure
  .eslintrc.js
  .github/workflows/ci.yml
  .github/workflows/release-package.yml
  .gitignore
  README.md
  dist/.keep
  esbuild.js
  package.json
  yarn.lock
Labels: chore

#10 Fix reference to private methods
  src/api_module.js
Labels: bug

#11 Add note about versioning in README
  README.md
Labels: documentation

#12 Import fetch-retry instead of using `require`
  src/api_module.js
Labels: bug

#13 Move `@babel/core` and `@babel/eslint-parser` to devDependencies
  package.json
Labels: chore

#14 Don't declare indexGenerator as async function
  src/api_module.js
Labels: bug

#15 Fix publishing of package
  .github/workflows/release-package.yml
Labels: chore

#19 Fix inconsistent module names
  src/index.js
Labels: bug

#17 Fix inconsistent `device_id`
  src/api_module.js
Labels: bug

#21 Run CI actions on pull request and pushes to tags or main branch
  .github/workflows/ci.yml
Labels: chore

#20 Edit publish action to create a release and publish on tag push
  .github/release-drafter.yml
  .github/workflows/release-package.yml
  .github/workflows/release.yml
Labels: chore

#18 Fix rescan paths
  README.md
  src/api_module.js
  src/index.js
Labels: bug

#22 Restructure modules
  .eslintrc.js
  README.md
  package.json
  src/api_module.js
  src/index.js
  src/scopes.js
  yarn.lock
Labels: refactor

#26 Don't set loaded in indexGenerator
  src/api_module.js
Labels: bug
